export ED="/usr/bin/nvim"
export EDITOR="/usr/bin/nvim"
export VISUAL="/usr/bin/nvim"
export SUDO_EDITOR="/usr/bin/nvim"
export PAGER="/usr/bin/less"
export BROWSER="/usr/bin/firefox"
export INPUTRC="$HOME/.inputrc"
#export LC_COLLATE="C"
#export LC_TIME=en_DK.UTF-8

# ANSI colors
#BLK='\e[0;30m'
#BLU='\e[0;34m'
#GRN='\e[0;32m'
#CYN='\e[0;36m'
#RED='\e[0;31m'
#PPL='\e[0;35m'
#BRN='\e[0;33m'
#LTGRY='\e[0;37m'
#DKGRY='\e[1;30m'
#LTBLU='\e[1;34m'
#LTGRN='\e[1;32m'
#LTCYN='\e[1;36m'
#LTRED='\e[1;31m'
#LTPPL='\e[1;35m'
#YEL='\e[1;33m'
#WHT='\e[1;37m'
#NON='\e[0m'
 
# tput colors
# BLK="$(tput setaf 0)"
# RED="$(tput setaf 1)"
# GRN="$(tput setaf 2)"
# YEL="$(tput setaf 3)"
# BLU="$(tput setaf 4)"
# MAG="$(tput setaf 5)"
# CYN="$(tput setaf 6)"
# WHT="$(tput setaf 7)"
# NON="$(tput sgr0)"

# GNU stow
export STOW_DIR="$HOME/.dot-pub"

# pet
export PET_GITHUB_ACCESS_TOKEN=`/bin/cat $HOME/.creds/pet`

# less
export LESS=-R
export LESSOPEN='|pygmentize -g %s'
export LESS_TERMCAP_mb=$'\E[1;31m'     # begin bold
export LESS_TERMCAP_md=$'\E[1;36m'     # begin blink
export LESS_TERMCAP_me=$'\E[0m'        # reset bold/blink
export LESS_TERMCAP_so=$'\E[01;44;33m' # begin reverse video
export LESS_TERMCAP_se=$'\E[0m'        # reset reverse video
export LESS_TERMCAP_us=$'\E[1;32m'     # begin underline
export LESS_TERMCAP_ue=$'\E[0m'        # reset underline

# ls
export LS_OPTIONS='--color=auto -A -F -X -B -h -v -b -T 0 --group-directories-first --quoting-style=shell-escape --time-style=iso'

# pip
#export PIP_USER=true	# PIP install as user - should already be default

# cheat
#export CHEAT_EDITOR='/bin/vi'
#export CHEAT_USER_DIR="$HOME/.local/share/cheat"
#export CHEAT_PATH="$HOME/.local/share/cheat:/usr/share/cheat"
#export CHEAT_COLORS='true' # requires python-pygments
#export CHEAT_COLORSCHEME='dark' # must be 'light' (default) or 'dark'
#export CHEAT_HIGHLIGHT='yellow' # requires termcolor

# git
#export GIT_PS1_SHOWDIRTYSTATE=1
#export GIT_PS1_SHOWSTASHSTATE=1
#export GIT_PS1_SHOWBRANCHREMOTE=1
#export GIT_PS1_SHOWUPSTREAM="verbose"
# GIT_CONFIG_PARAMETERS space separate for multiple ("'' '' ''")
export GIT_CONFIG_PARAMETERS="'user.name=$USER@$HOSTNAME'"

# java
# Set all Java apps to use GTK+ font & theme settings (https://wiki.manjaro.org/index.php?title=Set_all_Java_apps_to_use_GTK%2B_font_%26_theme_settings)
export _JAVA_OPTIONS="-Dawt.useSystemAAFontSettings=on -Dswing.aatext=true -Dswing.defaultlaf=com.sun.java.swing.plaf.gtk.GTKLookAndFeel -Dswing.crossplatformlaf=com.sun.java.swing.plaf.gtk.GTKLookAndFeel ${_JAVA_OPTIONS}"

# Consistent file dialog under KDE Plasma <https://wiki.archlinux.org/title/Uniform_look_for_Qt_and_GTK_applications#QGtkStyle>
# firefox use kde file chooser
# not working here? use /etc/environment?
# export GTK_USE_PORTAL=1
# export GDK_DEBUG=portals

# https://github.com/djui/alias-tips#customize-the-output
export ZSH_PLUGINS_ALIAS_TIPS_TEXT="Known Alias = "
export ZSH_PLUGINS_ALIAS_TIPS_FORCE=0
export ZSH_PLUGINS_ALIAS_TIPS_EXCLUDES="_ ll vi vim"

# zsh comments in interactive shell
setopt interactive_comments
